//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixAndUpdate.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FixAndUpdate.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] BLL {
            get {
                object obj = ResourceManager.GetObject("BLL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BLLp_manifest {
            get {
                return ResourceManager.GetString("BLLp_manifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ErrorLogger {
            get {
                object obj = ResourceManager.GetObject("ErrorLogger", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Interop_MSORUNLib {
            get {
                object obj = ResourceManager.GetObject("Interop_MSORUNLib", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Microsoft_Office_Interop_Word {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Office_Interop_Word", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;doc&gt;
        ///  &lt;assembly&gt;
        ///    &lt;name&gt;Microsoft.Office.Interop.Word&lt;/name&gt;
        ///  &lt;/assembly&gt;
        ///  &lt;members&gt;
        ///    &lt;member name=&quot;T:Microsoft.Office.Interop.Word._Application&quot;&gt;
        ///      &lt;summary&gt;Represents the Microsoft Office Word application. &lt;/summary&gt;
        ///    &lt;/member&gt;
        ///    &lt;member name=&quot;M:Microsoft.Office.Interop.Word._Application.Activate&quot;&gt;
        ///      &lt;summary&gt;Activates the specified object.&lt;/summary&gt;
        ///    &lt;/member&gt;
        ///    &lt;member name=&quot;P:Microsoft.Office.Interop.Word._Application.Active [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Microsoft_Office_Interop_Word1 {
            get {
                return ResourceManager.GetString("Microsoft_Office_Interop_Word1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Microsoft_Vbe_Interop {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Vbe_Interop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NumChakra {
            get {
                object obj = ResourceManager.GetObject("NumChakra", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///    &lt;configSections&gt;
        ///    &lt;/configSections&gt;
        ///    &lt;connectionStrings&gt;
        ///        &lt;add name=&quot;Omega.Properties.Settings.DBConnectionString&quot; connectionString=&quot;Provider=Microsoft.Jet.OLEDB.4.0;Data Source=G:\Documents\_Coding\Dot.Net\C#\Omega\DB.mdb&quot;
        ///            providerName=&quot;System.Data.OleDb&quot; /&gt;
        ///    &lt;/connectionStrings&gt;
        ///&lt;/configuration&gt;.
        /// </summary>
        public static string NumChakra_exe {
            get {
                return ResourceManager.GetString("NumChakra_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NumChakra_exe1 {
            get {
                object obj = ResourceManager.GetObject("NumChakra_exe1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NumChakra_vshost {
            get {
                object obj = ResourceManager.GetObject("NumChakra_vshost", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///    &lt;configSections&gt;
        ///    &lt;/configSections&gt;
        ///    &lt;connectionStrings&gt;
        ///        &lt;add name=&quot;Omega.Properties.Settings.DBConnectionString&quot; connectionString=&quot;Provider=Microsoft.Jet.OLEDB.4.0;Data Source=G:\Documents\_Coding\Dot.Net\C#\Omega\DB.mdb&quot;
        ///            providerName=&quot;System.Data.OleDb&quot; /&gt;
        ///    &lt;/connectionStrings&gt;
        ///&lt;/configuration&gt;.
        /// </summary>
        public static string NumChakra_vshost_exe {
            get {
                return ResourceManager.GetString("NumChakra_vshost_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NumChakra_vshost_exe1 {
            get {
                object obj = ResourceManager.GetObject("NumChakra_vshost_exe1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NumChakra_vshost1 {
            get {
                object obj = ResourceManager.GetObject("NumChakra_vshost1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NumChakra1 {
            get {
                object obj = ResourceManager.GetObject("NumChakra1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] office {
            get {
                object obj = ResourceManager.GetObject("office", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;doc&gt;
        ///  &lt;assembly&gt;
        ///    &lt;name&gt;office&lt;/name&gt;
        ///  &lt;/assembly&gt;
        ///  &lt;members&gt;
        ///    &lt;member name=&quot;T:Microsoft.Office.Core._CommandBarActiveX&quot;&gt;&lt;/member&gt;
        ///    &lt;member name=&quot;P:Microsoft.Office.Core._CommandBarActiveX.accChild(System.Object)&quot;&gt;
        ///      &lt;param name=&quot;varChild&quot;&gt;&lt;/param&gt;
        ///    &lt;/member&gt;
        ///    &lt;member name=&quot;P:Microsoft.Office.Core._CommandBarActiveX.accChildCount&quot;&gt;&lt;/member&gt;
        ///    &lt;member name=&quot;P:Microsoft.Office.Core._CommandBarActiveX.accDefaultAction(System.Object)&quot;&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string office1 {
            get {
                return ResourceManager.GetString("office1", resourceCulture);
            }
        }
    }
}
